# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-26 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlepage',
            options={'verbose_name': 'Article'},
        ),
        migrations.AddField(
            model_name='articlepage',
            name='heading',
            field=models.TextField(blank=True, help_text='The title of the article'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='body',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='The body text of the article'),
        ),
    ]
