# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-25 12:52
from __future__ import unicode_literals

from django.db import migrations
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20170428_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='content_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='Content Type tags, eg: "videos", "blogs", "free"', through='articles.ContentTag', to='taggit.Tag', verbose_name='Content Tags'),
        ),
    ]
