# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-24 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0002_auto_20170724_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpage',
            name='text_alignment',
            field=models.CharField(choices=[('tl', 'left'), ('tc', 'center')], default='left', help_text='Text Alignment', max_length=10),
        ),
    ]
