# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-25 15:34
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0004_auto_20171024_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('heading', wagtail.wagtailcore.blocks.RichTextBlock()), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock(template='static/display.html')), ('column_left', wagtail.wagtailcore.blocks.RichTextBlock(template='static/display.html')), ('column_right', wagtail.wagtailcore.blocks.RichTextBlock(template='static/display.html')), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()))),
        ),
    ]
