# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-19 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('static', '0005_auto_20171025_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpage',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
