# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-19 18:58
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20170519_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbackpage',
            old_name='from_address',
            new_name='feedback1_default_text',
        ),
        migrations.RenameField(
            model_name='feedbackpage',
            old_name='thank_you_text',
            new_name='feedback1_help_text',
        ),
        migrations.RenameField(
            model_name='feedbackpage',
            old_name='subject',
            new_name='feedback2_default_text',
        ),
        migrations.RemoveField(
            model_name='feedbackpage',
            name='to_address',
        ),
        migrations.AddField(
            model_name='feedbackpage',
            name='feedback1_intro',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='feedbackpage',
            name='feedback2_help_text',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='feedbackpage',
            name='feedback2_intro',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
