# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-02 14:49
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_auto_20170519_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackpage',
            name='alphatext',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='Explanation of the Alpha section'),
        ),
    ]
