# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-25 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_feedbackpage_alphatext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackpage',
            name='feedback1_default_text',
        ),
        migrations.RemoveField(
            model_name='feedbackpage',
            name='feedback1_help_text',
        ),
        migrations.RemoveField(
            model_name='feedbackpage',
            name='feedback1_intro',
        ),
        migrations.RemoveField(
            model_name='feedbackpage',
            name='feedback2_default_text',
        ),
        migrations.RemoveField(
            model_name='feedbackpage',
            name='feedback2_help_text',
        ),
        migrations.RemoveField(
            model_name='feedbackpage',
            name='feedback2_intro',
        ),
        migrations.RemoveField(
            model_name='feedbackpage',
            name='form_title',
        ),
        migrations.AddField(
            model_name='formfield',
            name='after_input',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='after input'),
        ),
        migrations.AddField(
            model_name='formfield',
            name='before_input',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='before input'),
        ),
        migrations.AlterField(
            model_name='feedbackpage',
            name='alphatext',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='Why to take part in the alpha'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time')], max_length=16, verbose_name='field type'),
        ),
    ]
