# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-02 15:37
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_feedbackpage_alphatext'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackpage',
            name='alpha',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='What is Alpha'),
        ),
        migrations.AlterField(
            model_name='feedbackpage',
            name='alphatext',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='Why to take part in the alpha'),
        ),
    ]
