# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 16:13
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_auto_20170602_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_form_fields', to='feedback.FeedbackPage'),
        ),
    ]
