# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-20 08:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0008_customformsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='after_input',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='help text'),
        ),
        migrations.AddField(
            model_name='formfield',
            name='before_input',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='help text'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('multiline', 'Multi-line text'), ('email', 'Email'), ('radio', 'Radio buttons')], max_length=16, verbose_name='field type'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='feedback.FeedbackPage'),
        ),
    ]
