# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-24 16:39
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='footer',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
