# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-02 10:25
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='alphatext',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
