# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-05 11:37
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_alphatext'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='lookingfor',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
