# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-07 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_homepage_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='assessment_text',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='Label for sleep assessment link'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='crisis_text',
            field=models.TextField(blank=True, help_text='Label for sleep crisis page link'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='filter_label_1',
            field=models.TextField(blank=True, help_text='Label/Question for first set of filters'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='filter_label_2',
            field=models.TextField(blank=True, help_text='Label/Question for second set of filters'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='filter_label_3',
            field=models.TextField(blank=True, help_text='Label/Question for third set of filters'),
        ),
    ]
