# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-15 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('home', '0011_auto_20170608_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image_position',
            field=models.TextField(blank=True, help_text='Values: center, top, right, bottom, left'),
        ),
    ]
