# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-19 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_homepage_hero_image_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL of an introductiary youtube video'),
        ),
    ]
