# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-21 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_homepage_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='quick_links',
            field=models.TextField(blank=True, help_text='Comma separated list of quick-links'),
        ),
    ]
