# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-03 13:41
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_homepage_quick_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='header',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='Hero title'),
        ),
    ]
