# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-17 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_homepage_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='Max file size: 10MB. Choose from: GIF, JPEG, PNG (but pick PNG if you have the choice)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
