# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-28 11:47
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcepage',
            name='body',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='A description of the resource'),
        ),
    ]
