# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-05 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_resourcepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcepage',
            name='priority',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default='5', help_text='Highest priority 1, lowest priority 5'),
        ),
    ]
