# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-05 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_resourcepage_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcepage',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL of a youtube video for the resource'),
        ),
    ]
