# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-05 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('resources', '0004_resourcepage_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiddenTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_hidden_items', to='resources.ResourcePage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources_hiddentag_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='resourcepage',
            name='hidden_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='Hidden tags for admin use', through='resources.HiddenTag', to='taggit.Tag', verbose_name='Hidden Tags'),
        ),
    ]
