# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-22 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('resources', '0006_auto_20170622_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='resourcepage',
            name='audience_tags',
        ),
        migrations.RemoveField(
            model_name='resourcepage',
            name='tags',
        ),
        migrations.AddField(
            model_name='resourcepage',
            name='issue_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='Issue tags, eg: "insomnia", "fatigue", "snoring"', through='resources.IssueTag', to='taggit.Tag', verbose_name='Issue Tags'),
        ),
        migrations.AddField(
            model_name='resourcepage',
            name='reason_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='Reason tags, eg: "loneliness", "relationships"', through='resources.ReasonTag', to='taggit.Tag', verbose_name='Reason Tags'),
        ),
        migrations.AlterField(
            model_name='issuetag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_issue_items', to='resources.ResourcePage'),
        ),
        migrations.AlterField(
            model_name='issuetag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources_issuetag_items', to='taggit.Tag'),
        ),
        migrations.AlterField(
            model_name='reasontag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_reason_items', to='resources.ResourcePage'),
        ),
        migrations.AlterField(
            model_name='reasontag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources_reasontag_items', to='taggit.Tag'),
        ),
        migrations.AddField(
            model_name='topictag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_topic_items', to='resources.ResourcePage'),
        ),
        migrations.AddField(
            model_name='topictag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources_topictag_items', to='taggit.Tag'),
        ),
        migrations.AddField(
            model_name='resourcepage',
            name='topic_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='Topic tags, eg: "sleep", "depression", "stress"', through='resources.TopicTag', to='taggit.Tag', verbose_name='Topic Tags'),
        ),
    ]
