# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-03 13:48
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_auto_20170622_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcepage',
            name='cons',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='A list of cons for the resource'),
        ),
        migrations.AddField(
            model_name='resourcepage',
            name='pros',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='A list of pros for the resource'),
        ),
    ]
