# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-18 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('wagtailcore', '0033_remove_golive_expiry_help_text'),
        ('resources', '0009_resourceindexpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('banner', wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='Banner at the top of every page')),
                ('header', wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='Hero title')),
                ('body', wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='Description of page')),
                ('filter_label_1', models.TextField(blank=True, help_text='Label/Question for first set of filters')),
                ('filter_label_2', models.TextField(blank=True, help_text='Label/Question for second set of filters')),
                ('filter_label_3', models.TextField(blank=True, help_text='Label/Question for third set of filters')),
                ('assessment_text', wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='Label for sleep assessment link')),
                ('crisis_text', wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='Label for sleep crisis page link')),
                ('lookingfor', wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='Information on how to leave suggestions and what the suggestions are for')),
                ('alpha', wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='What is Alpha')),
                ('alphatext', wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='Why to take part in the alpha')),
                ('footer', wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='Footer text')),
                ('video_url', models.URLField(blank=True, help_text='URL of an introductiary youtube video')),
                ('hero_image', models.ForeignKey(blank=True, help_text='Max file size: 10MB. Choose from: GIF, JPEG, PNG (but pick PNG if you have the choice)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
