# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-08 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('resources', '0011_formfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcludeTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_exclude_items', to='resources.Home')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources_excludetag_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='home',
            name='exclude_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='Tags you do not want to show in the filters for this home page', through='resources.ExcludeTag', to='taggit.Tag', verbose_name='Exclude Tags'),
        ),
    ]
