# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-24 11:09
from __future__ import unicode_literals

import colorful.fields
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('resources', '0013_resourceformfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcepage',
            name='background_color',
            field=colorful.fields.RGBColorField(blank=True, default='#ffffff', help_text='The background colour to use if there is no hero image', null=True),
        ),
        migrations.AddField(
            model_name='resourcepage',
            name='brand_logo',
            field=models.ForeignKey(blank=True, help_text='\n            Max file size: 10MB. Choose from: GIF, JPEG, PNG\n            (but pick PNG if you have the choice)\n        ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='resourcepage',
            name='brand_text',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='resourcepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='\n            Max file size: 10MB. Choose from: GIF, JPEG, PNG\n            (but pick PNG if you have the choice)\n        ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='resourcepage',
            name='text_color',
            field=colorful.fields.RGBColorField(blank=True, default='#000000', help_text='\n            The colour of the brand text.\n            It should contrast well with the background colour or image\n        ', null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='exclude_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='\n        Tags you do not want to show in the filters for this home page\n        ', through='resources.ExcludeTag', to='taggit.Tag', verbose_name='Exclude Tags'),
        ),
        migrations.AlterField(
            model_name='home',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='\n            Max file size: 10MB. Choose from: GIF, JPEG, PNG\n            (but pick PNG if you have the choice)\n        ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='home',
            name='lookingfor',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='\n        Information on how to leave suggestions and what they are for\n        '),
        ),
        migrations.AlterField(
            model_name='resourcepage',
            name='content_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='\n            Content Type tags, eg: "videos", "blogs", "free", "subscription"\n        ', through='resources.ContentTag', to='taggit.Tag', verbose_name='Content Tags'),
        ),
    ]
