# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-25 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0014_auto_20170824_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcepage',
            name='resource_url_text',
            field=models.TextField(blank=True, help_text='The text for the url link'),
        ),
    ]
