# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-31 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.wagtailcore.fields
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0016_homefooterlinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeFooterBlocks',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False,serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.TextField(blank=True)),
                ('description', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('link_text', models.TextField(blank=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_blocks', to='resources.Home')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
