# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-01 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0033_remove_golive_expiry_help_text'),
        ('resources', '0017_homefooterblocks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homefooterblocks',
            name='link',
        ),
        migrations.AddField(
            model_name='homefooterblocks',
            name='link_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
