# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-07 14:58
from __future__ import unicode_literals

import colorful.fields
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0021_auto_20170904_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourcePageBadges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('badge_color', colorful.fields.RGBColorField(blank=True, default='#ffffff', null=True)),
                ('badge_text_color', colorful.fields.RGBColorField(blank=True, default='#000000', null=True)),
                ('badge_text', models.TextField(blank=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='resources.ResourcePage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='home',
            name='description',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='\n        A short description of the page that will show on the homepage\n    '),
        ),
    ]
