# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-06 10:06
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0021_auto_20170904_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='description',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='\n        A short description of the page that will show on the homepage\n    '),
        ),
    ]
