# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-12 12:24
from __future__ import unicode_literals

import colorful.fields
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import resources.models.resources


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0023_tip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('resourcepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.ResourcePage')),
            ],
            options={
                'abstract': False,
            },
            bases=('resources.resourcepage',),
        ),
        migrations.CreateModel(
            name='ResourcePageBadges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('badge_color', colorful.fields.RGBColorField(blank=True, default='#ffffff', null=True)),
                ('badge_text_color', colorful.fields.RGBColorField(blank=True, default='#000000', null=True)),
                ('badge_text', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='resourcepage',
            name='latitude',
            field=resources.models.resources.LatitudeField(blank=True, help_text='\n            latitude. This should be a number between -90 and 90\n        ', max_length=255),
        ),
        migrations.AddField(
            model_name='resourcepage',
            name='longitude',
            field=resources.models.resources.LongitudeField(blank=True, help_text='\n            longitude. This should be a number between -180 and 180\n        ', max_length=255),
        ),
        migrations.AddField(
            model_name='resourcepagebadges',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='resources.ResourcePage'),
        ),
    ]
