# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-14 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import resources.models.home


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('resources', '0024_auto_20170912_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeLocationImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('first_letters_of_zip', resources.models.home.TwoCharsZipcodeField(blank=True, help_text='\n            The first letter or letters of the postcode\n            you would like to match with, e.g. TW or E\n        ', max_length=255)),
                ('location_image', models.ForeignKey(blank=True, help_text='\n            Max file size: 10MB. Choose from: GIF, JPEG, PNG\n            (but pick PNG if you have the choice)\n        ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_images', to='resources.Home')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
