# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-14 11:12
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0025_homelocationimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomeLocationImages',
            new_name='MainLocationImages',
        ),
        migrations.AlterField(
            model_name='mainlocationimages',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_images', to='resources.Main'),
        ),
    ]
