# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-17 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0026_auto_20170915_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='algorithm_id',
            field=models.IntegerField(default=4648, help_text='The ID of the assessment algorithm'),
        ),
    ]
