# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-15 10:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0025_remove_resourcepage_video_url'),
        ('resources', '0026_auto_20170914_1112'),
    ]

    operations = [
    ]
