# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-10 13:51
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0028_latlong'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='sub_body',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='Text for below the description of the page'),
        ),
    ]
