# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-12 11:39
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0029_home_sub_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='resource_text',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='An intro to the resources attached to the assessment results'),
        ),
    ]
