# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-13 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0030_assessment_resource_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourcePageButtons',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False,serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('button_type', models.CharField(choices=[('Primary', 'Primary'), ('Secondary', 'Secondary')], default='Primary', help_text='Type of Button - Primary/Secondary', max_length=16)),
                ('button_text', models.TextField()),
                ('button_link', models.URLField()),
                ('alignment', models.CharField(choices=[('tl', 'left'), ('tc', 'center'), ('tr', 'right')], default='left', help_text='Alignment of the button', max_length=10)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='resources.ResourcePage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
