# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-24 08:43
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0032_auto_20171024_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='pyr_text',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='PYR explanation'),
        ),
    ]
