# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-25 11:10
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0033_home_pyr_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcepage',
            name='tagline',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='Bold text that displays on the resource list'),
        ),
        migrations.AlterField(
            model_name='resourcepage',
            name='body',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='A more detailed description of the resource'),
        ),
    ]
