# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-07 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0033_remove_golive_expiry_help_text'),
        ('resources', '0034_auto_20171025_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='banner_button_1_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='main',
            name='banner_button_1_text',
            field=models.TextField(blank=True, help_text='Text for first button'),
        ),
        migrations.AddField(
            model_name='main',
            name='banner_button_2_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='main',
            name='banner_button_2_text',
            field=models.TextField(blank=True, help_text='Text for second button'),
        ),
    ]
