# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-19 05:40
from __future__ import unicode_literals

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0035_auto_20171107_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='link_color',
            field=colorful.fields.RGBColorField(blank=True, default='#f3a140', help_text="The link's background colour to use on homepage", null=True),
        ),
    ]
