# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-19 04:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0033_remove_golive_expiry_help_text'),
        ('resources', '0037_auto_20180419_0442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homefooterlinksone',
            name='footer_image',
        ),
        migrations.RemoveField(
            model_name='homefooterlinksone',
            name='footer_link',
        ),
        migrations.AddField(
            model_name='homefooterlinksone',
            name='link_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='homefooterlinksone',
            name='link_text',
            field=models.TextField(blank=True),
        ),
    ]
