# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-19 04:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('resources', '0038_auto_20180419_0451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homefooterlinkstwo',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='homefooterlinkstwo',
            name='link_text',
        ),
        migrations.AddField(
            model_name='homefooterlinkstwo',
            name='footer_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homefooterlinkstwo',
            name='footer_link',
            field=models.URLField(blank=True),
        ),
    ]
