# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-19 05:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0039_auto_20180419_0453'),
        ('resources', '0036_home_link_color'),
    ]

    operations = [
    ]
