# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-19 09:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0040_merge_20180419_0552'),
        ('resources', '0040_auto_20180419_0607'),
    ]

    operations = [
    ]
