# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-19 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0042_resourcepage_logo_background_color'),
        ('resources', '0041_merge_20180419_0927'),
    ]

    operations = [
    ]
