# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-20 04:23
from __future__ import unicode_literals

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0043_merge_20180419_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcepage',
            name='logo_background_color',
            field=colorful.fields.RGBColorField(blank=True, default='#16b28f', help_text='The background colour of brand_logo', null=True),
        ),
    ]
