# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-23 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0045_homecollections'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='collections_tagline',
            field=models.TextField(blank=True, help_text='Tagline of collections'),
        ),
        migrations.AddField(
            model_name='home',
            name='collections_title',
            field=models.TextField(blank=True, help_text='Title of collections'),
        ),
    ]
