# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-03 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0051_auto_20180426_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopResources',
            fields=[
                ('resourcepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.ResourcePage')),
                ('collection_heading', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('button_text', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('resources.resourcepage',),
        ),
    ]
