# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-04 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0053_resourcepageselectresources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homecollections',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='homecollections',
            name='page',
        ),
        migrations.DeleteModel(
            name='HomeCollections',
        ),
    ]
