# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-07 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0054_auto_20180504_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homesitemap',
            name='link_text',
        ),
    ]
