# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-10 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('resources', '0056_auto_20180508_0525'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionsIndexPage',
            fields=[
                ('resourcepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.ResourcePage')),
                ('image_text', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('body_text', models.TextField(blank=True)),
                ('collections_cover_image', models.ForeignKey(blank=True, help_text='\n            Max file size: 10MB. Choose from: GIF, JPEG, PNG\n            (but pick PNG if you have the choice)\n        ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('resources.resourcepage',),
        ),
    ]
