# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-14 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0057_collectionsindexpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionsindexpage',
            name='body_text',
            field=models.TextField(blank=True, help_text='Text that displays on the body'),
        ),
        migrations.AlterField(
            model_name='collectionsindexpage',
            name='collections_cover_image',
            field=models.ForeignKey(blank=True, help_text='\n            Max file size: 10MB. Choose from: JPEG, PNG\n        ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='collectionsindexpage',
            name='image_text',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='Text that displays hover the image'),
        ),
        migrations.AlterField(
            model_name='homefooterlinks',
            name='footer_image',
            field=models.ForeignKey(blank=True, help_text='\n            Max file size: 10MB. Choose from: JPEG, PNG\n        ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='resourcecollections',
            name='collection_heading',
            field=models.TextField(blank=True, help_text='Heading of collections'),
        ),
        migrations.AlterField(
            model_name='resourcecollections',
            name='description',
            field=models.TextField(blank=True, help_text='Short description of collections'),
        ),
        migrations.AlterField(
            model_name='results',
            name='cover_image',
            field=models.ForeignKey(blank=True, help_text='\n            Max file size: 10MB. Choose from: JPEG, PNG\n        ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='results',
            name='image_text',
            field=models.TextField(blank=True, help_text='Text that displays hover the image'),
        ),
    ]
