# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-16 05:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0058_auto_20180514_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcepage',
            name='brand_logo',
            field=models.ForeignKey(blank=True, help_text='\n            Max file size: 10MB. Choose from: JPEG, PNG\n            (Please upload 155x60 image)\n        ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
