# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-16 06:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('resources', '0059_auto_20180516_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcecollections',
            name='body_text',
            field=models.TextField(blank=True, help_text='Text that displays on the body'),
        ),
        migrations.AddField(
            model_name='resourcecollections',
            name='collection_cover_image',
            field=models.ForeignKey(blank=True, help_text='\n            Max file size: 10MB. Choose from: JPEG, PNG\n        ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='resourcecollections',
            name='image_text',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='Text that displays hover the image'),
        ),
    ]
