# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-16 06:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0060_auto_20180516_0636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionsindexpage',
            name='body_text',
        ),
        migrations.RemoveField(
            model_name='collectionsindexpage',
            name='collections_cover_image',
        ),
        migrations.RemoveField(
            model_name='collectionsindexpage',
            name='image_text',
        ),
    ]
