# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-16 12:06
from __future__ import unicode_literals

import colorful.fields
from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('wagtailcore', '0033_remove_golive_expiry_help_text'),
        ('resources', '0061_auto_20180516_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='block_background_color',
            field=colorful.fields.RGBColorField(blank=True, default='#242e51', help_text="The result block's background colour", null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='body_content',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='\n        Body of result block\n    ', max_length=206),
        ),
        migrations.AddField(
            model_name='home',
            name='button_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='home',
            name='footer_content',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='\n        Footer of result block\n    ', max_length=206),
        ),
        migrations.AddField(
            model_name='home',
            name='image',
            field=models.ForeignKey(blank=True, help_text='\n            Max file size: 10MB. Choose from: JPEG, PNG\n        ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='home',
            name='result_heading',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='\n        Heading of result block\n    ', max_length=206),
        ),
    ]
