# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-16 09:58
from __future__ import unicode_literals

import colorful.fields
from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0061_auto_20180516_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='background_color',
            field=colorful.fields.RGBColorField(blank=True, default='#242e51', help_text="The result block's background colour", null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='body_content',
            field=wagtail.wagtailcore.fields.StreamField((('heading', wagtail.wagtailcore.blocks.RichTextBlock()), ('column_left', wagtail.wagtailcore.blocks.RichTextBlock()), ('column_right', wagtail.wagtailcore.blocks.RichTextBlock()), ('footer_content', wagtail.wagtailcore.blocks.RichTextBlock())), blank=True),
        ),
    ]
