# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-08-24 08:59
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0066_homesubmenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homesubmenu',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_menu', to='resources.Home'),
        ),
    ]
